#ifndef COMMON_H
#define COMMON_H

namespace common{

enum DIR {UP, DOWN, LEFT, RIGHT};
enum PLAYERCOLOR{ RED, GREEN, BLUE, YELLOW};

enum COLOR{ SWAMP, MOUNTAIN, WHEATFIELD, FOREST, LAKE, PASTURE, EMPTY, CASTLE};

}

#endif //COMMON_H;
