#ifndef COMMON_H
#define COMMON_H

namespace common{

enum DIR {UP, DOWN, LEFT, RIGHT};
enum COLOR{ SWAMP, MOUNTAIN, WHEATFIELD, FOREST, LAKE, PASTURE, EMPTY, CASTLE};
enum COLOR{ RED, GREEN, BLUE, YELLOW};
}

#endif //COMMON_H;
